### ISSUE TITLE
Checklist de práticas 

### ISSUE THREAD

**Issue by AurianLira** [AurianLira/GCMS-Aurian-Lira#2]
@ramidedantas 

Itens do checklist:

- [ ] Instalar Git localmente
- [ ]  Criar projeto local
- [ ]  Criar repositório local e realizar commits
- [ ]  Subir alterações para o repositório remoto
- [ ]  Fazer alterações no repositório da turma

**Comment by ramidedantas** [comment]
@AurianLira verifique formato da checklist (falta caixas de marcação).

**Comment by AurianLira** [comment]
@ramidedantas corrigi professor, verifique se está correto por favor

**Comment by ramidedantas** [comment]
@AurianLira ok agora.
